import pep8
import os
import unittest

from django.conf import settings

# ignore autogenerated files and imported library code
EXCLUDED = ['*migrations*', 'env*', 'build*']
PATHS = [settings.PROJECT_ROOT]

# ignore line too long
IGNORE = ['E501']


class Pep8Test(unittest.TestCase):

    def test_pep8(self):

        options_dict = {
            'paths': PATHS,
            'exclude': EXCLUDED,
            'ignore': IGNORE,
        }

        pep8style = pep8.StyleGuide(**options_dict)
        report = pep8style.check_files()

        self.assertEquals(report.get_count(), 0, 'No pep8 errors')
